#!/bin/bash
set -eEuo pipefail

apt-get update
apt-get install --no-install-recommends --yes \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install --no-install-recommends --yes \
    docker-ce \
    docker-ce-cli \
    containerd.io

mkdir --parent /etc/docker
cat <<EOF > /etc/docker/daemon.json
{
  "storage-driver": "devicemapper"
}
EOF
