#!/bin/bash
set -eEuo pipefail

cd /etc/update-motd.d/

chmod -x 00-header \
        10-help-text \
        50-motd-news \
        85-fwupd \
        88-esm-announce \
        90-updates-available \
        91-contract-ua-esm-status \
        91-release-upgrade \
        92-unattended-upgrades \
        95-hwe-eol \
        98-fsck-at-reboot \
        98-reboot-required
