name: Build ISO

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  ISO_NAME: custom-ubuntu.iso

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build ISO
        run: |
            make iso
            ls -lh "${GITHUB_WORKSPACE}/out/$ISO_NAME"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${GITHUB_WORKSPACE}/out/$ISO_NAME"
